.TH SBTEDIT 1 2016-09-01 NCBI "NCBI Tools User's Manual"
.SH NAME
sbtedit \- GenBank submission template editor
.SH SYNOPSIS
.B sbtedit
.SH DESCRIPTION
\fBsbtedit\fP is a graphical editor for GenBank submission templates,
which \fBPsequin\fP(1) and \fBtbl2asn\fP(1) can combine with
sequence-specific data to produce complete submissions.
.SH AUTHOR
The National Center for Biotechnology Information.
.SH SEE ALSO
.ad l
.BR Psequin (1),
.BR tbl2asn (1).
