/***********************************************************************
*
**
*        Automatic header module from ASNTOOL
*
************************************************************************/

#ifndef _ASNTOOL_
#include <asn.h>
#endif

static char * asnfilename = "asnneten.l60";
static AsnValxNodePtr avn;
static AsnTypePtr at;
static AsnModulePtr amp;


/**************************************************
*
*    Defines for Module NCBI-Entrez
*
**************************************************/

#define ENTREZ_REQUEST &at[10]
#define ENTREZ_REQUEST_init &at[11]
#define ENTREZ_REQUEST_init_version &at[12]
#define ENTREZ_REQUEST_maxlinks &at[15]
#define ENTREZ_REQUEST_eval &at[17]
#define ENTREZ_REQUEST_docsum &at[53]
#define ENTREZ_REQUEST_linkuidlist &at[64]
#define ENTREZ_REQUEST_uidlinks &at[73]
#define ENTREZ_REQUEST_byterm &at[74]
#define ENTREZ_REQUEST_bypage &at[80]
#define ENTREZ_REQUEST_findterm &at[86]
#define ENTREZ_REQUEST_fini &at[91]
#define ENTREZ_REQUEST_createnamed &at[92]
#define ENTREZ_REQUEST_getmle &at[98]
#define ENTREZ_REQUEST_getseq &at[99]
#define ENTREZ_REQUEST_evalX &at[104]
#define ENTREZ_REQUEST_createnamedX &at[105]
#define ENTREZ_REQUEST_seqidforgi &at[112]
#define ENTREZ_REQUEST_findseqid &at[113]
#define ENTREZ_REQUEST_canneighbortext &at[114]
#define ENTREZ_REQUEST_expanded_medline &at[115]
#define ENTREZ_REQUEST_get_hierarchy &at[116]
#define ENTREZ_REQUEST_neighbortext &at[117]
#define ENTREZ_REQUEST_eval_count &at[125]
#define ENTREZ_REQUEST_initX &at[126]
#define ENTREZ_REQUEST_initX_version &at[127]
#define ENTREZ_REQUEST_getbiostr &at[128]
#define ENTREZ_REQUEST_getbiostrX &at[129]
#define REQUEST_getbiostrX_complexity &at[130]
#define ENTREZ_REQUEST_getbiostrX_get &at[131]
#define REQUEST_getbiostrX_max_models &at[132]
#define ENTREZ_REQUEST_extrainfo &at[133]
#define ENTREZ_REQUEST_blast &at[134]
#define ENTREZ_REQUEST_docsumX &at[142]
#define ENTREZ_REQUEST_getgenome &at[143]
#define ENTREZ_REQUEST_cluster_arts &at[144]
#define ENTREZ_REQUEST_getbiostrannot &at[151]
#define REQUEST_getbiostr_feat_ids &at[152]
#define REQUEST_getbiostr_annot_by_fid &at[157]

#define ENTREZ_TERMGET &at[18]
#define ENTREZ_TERMGET_max &at[19]
#define ENTREZ_TERMGET_cls &at[21]
#define ENTREZ_TERMGET_terms &at[24]
#define ENTREZ_TERMGET_date_constraints &at[44]

#define ENTREZ_DOCGET &at[54]
#define ENTREZ_DOCGET_class &at[55]
#define ENTREZ_DOCGET_mark_missing &at[56]
#define ENTREZ_DOCGET_ids &at[58]
#define ENTREZ_DOCGET_defer_count &at[63]

#define LINK_SETGET &at[65]
#define LINK_SETGET_max &at[66]
#define LINK_SETGET_link_to_cls &at[67]
#define LINK_SETGET_query_cls &at[68]
#define LINK_SETGET_mark_missing &at[69]
#define LINK_SETGET_query_size &at[70]
#define LINK_SETGET_query &at[71]
#define LINK_SETGET_query_E &at[72]

#define ENTREZ_TERM_BY_TERM &at[75]
#define ENTREZ_TERM_BY_TERM_type &at[76]
#define ENTREZ_TERM_BY_TERM_fld &at[77]
#define ENTREZ_TERM_BY_TERM_term &at[78]
#define ENTREZ_TERM_BY_TERM_num_terms &at[79]

#define ENTREZ_TERM_BY_PAGE &at[81]
#define ENTREZ_TERM_BY_PAGE_type &at[82]
#define ENTREZ_TERM_BY_PAGE_fld &at[83]
#define ENTREZ_TERM_BY_PAGE_page &at[84]
#define ENTREZ_TERM_BY_PAGE_num_pages &at[85]

#define TERM_LOOKUP &at[87]
#define TERM_LOOKUP_type &at[88]
#define TERM_LOOKUP_fld &at[89]
#define TERM_LOOKUP_term &at[90]

#define ENTREZ_NAMED_LIST &at[93]
#define ENTREZ_NAMED_LIST_term &at[94]
#define ENTREZ_NAMED_LIST_type &at[95]
#define ENTREZ_NAMED_LIST_fld &at[96]
#define ENTREZ_NAMED_LIST_uids &at[97]

#define ENTREZ_SEQGET &at[100]
#define ENTREZ_SEQGET_retype &at[101]
#define ENTREZ_SEQGET_mark_missing &at[102]
#define ENTREZ_SEQGET_ids &at[103]

#define ENTREZ_NAMED_LISTX &at[106]
#define ENTREZ_NAMED_LISTX_term &at[107]
#define ENTREZ_NAMED_LISTX_type &at[108]
#define ENTREZ_NAMED_LISTX_fld &at[109]
#define ENTREZ_NAMED_LISTX_uids &at[110]

#define ENTREZ_NEIGHBOR_TEXT &at[118]
#define ENTREZ_NEIGHBOR_TEXT_fld &at[119]
#define TEXT_percent_terms_to_use &at[120]
#define NEIGHBOR_TEXT_max_neighbors &at[121]
#define ENTREZ_NEIGHBOR_TEXT_min_score &at[122]
#define NEIGHBOR_TEXT_normal_text &at[123]
#define NEIGHBOR_TEXT_special_text &at[124]

#define ENTREZ_BLASTREQ &at[135]
#define ENTREZ_BLASTREQ_bsp &at[136]
#define ENTREZ_BLASTREQ_bsp_database &at[137]
#define ENTREZ_BLASTREQ_program &at[138]
#define ENTREZ_BLASTREQ_database &at[139]
#define ENTREZ_BLASTREQ_options &at[140]
#define ENTREZ_BLASTREQ_showprogress &at[141]

#define CLUSTER_ARTICLES &at[145]
#define CLUSTER_ARTICLES_ids &at[146]
#define CLUSTER_ARTICLES_fld &at[147]
#define CLUSTER_ARTICLES_min_cluster &at[148]
#define CLUSTER_ARTICLES_max_cluster &at[149]
#define CLUSTER_ARTICLES_max_terms &at[150]

#define GET_FEAT_IDS &at[153]
#define GET_FEAT_IDS_mmdbid &at[154]
#define GET_FEAT_IDS_feature_type &at[155]
#define GET_FEAT_IDS_feature_set_id &at[156]

#define GET_BY_FID &at[158]
#define GET_BY_FID_mmdbid &at[159]
#define GET_BY_FID_feature_id &at[160]
#define GET_BY_FID_feature_set_id &at[161]

#define ENTREZ_IDS &at[59]
#define ENTREZ_IDS_numid &at[60]
#define ENTREZ_IDS_ids &at[61]
#define ENTREZ_IDS_ids_E &at[62]

#define ENTREZ_FIELD &at[33]

#define CLUSTER_RESP &at[162]
#define CLUSTER_RESP_count &at[163]
#define CLUSTER_RESP_terms &at[164]
#define CLUSTER_RESP_terms_E &at[165]
#define CLUSTER_RESP_term_counts &at[166]
#define CLUSTER_RESP_term_counts_E &at[167]

#define ENTREZ_CLASS &at[22]

#define ENTREZ_TERM_LIST &at[25]
#define ENTREZ_TERM_LIST_E &at[26]
#define ENTREZ_TERM_LIST_E_operator &at[27]
#define ENTREZ_TERM_LIST_E_sp_operand &at[29]
#define ENTREZ_TERM_LIST_E_tot_operand &at[36]

#define DATE_CONSTRAINTS &at[45]
#define DATE_CONSTRAINTS_count &at[46]
#define DATE_CONSTRAINTS_date_vec &at[47]
#define DATE_CONSTRAINTS_date_vec_E &at[48]

#define DATE_VECTOR &at[49]
#define DATE_VECTOR_begin_date &at[50]
#define DATE_VECTOR_end_date &at[51]
#define DATE_VECTOR_field_abbr &at[52]

#define ENTREZ_OPERATOR &at[28]

#define SPECIAL_OPERAND &at[30]
#define SPECIAL_OPERAND_term &at[31]
#define SPECIAL_OPERAND_fld &at[32]
#define SPECIAL_OPERAND_type &at[34]
#define SPECIAL_OPERAND_high_range &at[35]

#define TOTAL_OPERAND &at[37]
#define TOTAL_OPERAND_term &at[38]
#define TOTAL_OPERAND_fld &at[39]
#define TOTAL_OPERAND_type &at[40]
#define TOTAL_OPERAND_high_range &at[41]

#define ENTREZ_BACK &at[168]
#define ENTREZ_BACK_error &at[169]
#define ENTREZ_BACK_init &at[170]
#define ENTREZ_BACK_init_e_info &at[171]
#define ENTREZ_BACK_maxlinks &at[172]
#define ENTREZ_BACK_eval &at[173]
#define ENTREZ_BACK_eval_bad_count &at[174]
#define ENTREZ_BACK_eval_link_set &at[175]
#define ENTREZ_BACK_docsum &at[176]
#define ENTREZ_BACK_docsum_ml &at[177]
#define ENTREZ_BACK_docsum_seq &at[189]
#define ENTREZ_BACK_docsum_str &at[198]
#define ENTREZ_BACK_linkuidlist &at[199]
#define ENTREZ_BACK_uidlinks &at[204]
#define ENTREZ_BACK_byterm &at[205]
#define ENTREZ_BACK_bypage &at[216]
#define ENTREZ_BACK_findterm &at[217]
#define ENTREZ_BACK_fini &at[222]
#define ENTREZ_BACK_createnamed &at[223]
#define ENTREZ_BACK_getmle &at[224]
#define ENTREZ_BACK_getseq &at[230]
#define ENTREZ_BACK_evalX &at[236]
#define ENTREZ_BACK_createnamedX &at[237]
#define ENTREZ_BACK_seqidforgi &at[238]
#define ENTREZ_BACK_findseqid &at[239]
#define ENTREZ_BACK_canneighbortext &at[240]
#define ENTREZ_BACK_expanded_medline &at[241]
#define ENTREZ_BACK_get_hierarchy &at[242]
#define ENTREZ_BACK_neighbortext &at[257]
#define ENTREZ_BACK_eval_count &at[258]
#define ENTREZ_BACK_getbiostr &at[259]
#define ENTREZ_BACK_getbiostrX &at[265]
#define ENTREZ_BACK_extrainfo &at[266]
#define ENTREZ_BACK_blast &at[272]
#define ENTREZ_BACK_blast_bad_count &at[273]
#define ENTREZ_BACK_blast_link_set &at[274]
#define ENTREZ_BACK_blast_job_start &at[275]
#define ENTREZ_BACK_blast_job_progress &at[276]
#define ENTREZ_BACK_docsumX &at[277]
#define ENTREZ_BACK_getgenome &at[283]
#define ENTREZ_BACK_cluster_arts &at[284]
#define ENTREZ_BACK_getbiostrannot &at[285]
#define ENTREZ_BACK_getbiostr_feat_ids &at[286]
#define BACK_getbiostr_annot_by_fid &at[287]

#define ML_SUMMARY_LIST &at[178]
#define ML_SUMMARY_LIST_num &at[179]
#define ML_SUMMARY_LIST_data &at[180]
#define ML_SUMMARY_LIST_data_E &at[181]

#define SEQ_SUMMARY_LIST &at[190]
#define SEQ_SUMMARY_LIST_num &at[191]
#define SEQ_SUMMARY_LIST_data &at[192]
#define SEQ_SUMMARY_LIST_data_E &at[193]

#define MARKED_LINK_SET &at[200]
#define MARKED_LINK_SET_link_set &at[201]
#define MARKED_LINK_SET_uids_processed &at[202]
#define MARKED_LINK_SET_marked_missing &at[203]

#define ENTREZ_TERM_RESP &at[206]
#define ENTREZ_TERM_RESP_num_terms &at[207]
#define ENTREZ_TERM_RESP_first_page &at[208]
#define ENTREZ_TERM_RESP_pages_read &at[209]
#define ENTREZ_TERM_RESP_info &at[210]
#define ENTREZ_TERM_RESP_info_E &at[211]

#define TERM_COUNTS &at[218]
#define TERM_COUNTS_found &at[219]
#define TERM_COUNTS_spec_count &at[220]
#define TERM_COUNTS_tot_count &at[221]

#define ENTREZ_MEDLINE_ENTRY_LIST &at[225]
#define ENTREZ_MEDLINE_ENTRY_LIST_num &at[226]
#define ENTREZ_MEDLINE_ENTRY_LIST_data &at[227]
#define MEDLINE_ENTRY_LIST_data_E &at[228]
#define ENTRY_LIST_marked_missing &at[229]

#define ENTREZ_SEQ_ENTRY_LIST &at[231]
#define ENTREZ_SEQ_ENTRY_LIST_num &at[232]
#define ENTREZ_SEQ_ENTRY_LIST_data &at[233]
#define ENTREZ_SEQ_ENTRY_LIST_data_E &at[234]
#define SEQ_ENTRY_LIST_marked_missing &at[235]

#define ENTREZ_TREE &at[243]
#define ENTREZ_TREE_num_in_lineage &at[244]
#define ENTREZ_TREE_num_children &at[245]
#define ENTREZ_TREE_term &at[246]
#define ENTREZ_TREE_lineage &at[247]
#define ENTREZ_TREE_lineage_E &at[248]
#define ENTREZ_TREE_children &at[249]
#define ENTREZ_TREE_children_E &at[250]
#define ENTREZ_TREE_canonical_form &at[256]

#define ENTREZ_BIOSTRUC_LIST &at[260]
#define ENTREZ_BIOSTRUC_LIST_num &at[261]
#define ENTREZ_BIOSTRUC_LIST_data &at[262]
#define ENTREZ_BIOSTRUC_LIST_data_E &at[263]
#define BIOSTRUC_LIST_marked_missing &at[264]

#define ENTREZ_EXTRA_INFO &at[267]
#define ENTREZ_EXTRA_INFO_maxlinks &at[268]
#define EXTRA_INFO_canneighbortext &at[269]
#define EXTRA_INFO_expanded_medline &at[270]
#define ENTREZ_EXTRA_INFO_canblast &at[271]

#define NEW_SUMMARY_LIST &at[278]
#define NEW_SUMMARY_LIST_num &at[279]
#define NEW_SUMMARY_LIST_type &at[280]
#define NEW_SUMMARY_LIST_data &at[281]
#define NEW_SUMMARY_LIST_data_E &at[282]

#define ML_SUMMARY &at[182]
#define ML_SUMMARY_muid &at[183]
#define ML_SUMMARY_no_abstract &at[184]
#define ML_SUMMARY_translated_title &at[185]
#define ML_SUMMARY_no_authors &at[186]
#define ML_SUMMARY_caption &at[187]
#define ML_SUMMARY_title &at[188]

#define SEQ_SUMMARY &at[194]
#define SEQ_SUMMARY_id &at[195]
#define SEQ_SUMMARY_caption &at[196]
#define SEQ_SUMMARY_title &at[197]

#define TERM_PAGE_INFO &at[212]
#define TERM_PAGE_INFO_term &at[213]
#define TERM_PAGE_INFO_spec_count &at[214]
#define TERM_PAGE_INFO_tot_count &at[215]

#define ENTREZ_TREE_CHILD &at[251]
#define ENTREZ_TREE_CHILD_name &at[252]
#define ENTREZ_TREE_CHILD_is_leaf_node &at[253]
#define ENTREZ_TREE_CHILD_special &at[254]
#define ENTREZ_TREE_CHILD_total &at[255]
