#!/bin/sh
#
# $Id: makeallchives,v 1.52 2002/05/21 20:04:15 beloslyu Exp $
#
#
# Creates all archives from a directory above 'ncbi'
#
# based on mkarchive written by
# J. Epstein, 9/29/95
#   modified to work in a distributed environment 3/13/98 (Friday the 13th)
#    -Karl Sirotkin
#
PATH=/bin:/usr/bin:$PATH
export PATH

if [ ! -d ncbi ] ; then
	echo must be executed above \'ncbi\' 
	exit 1
fi
if [ ! -d ncbi/build ] ; then
	echo must be executed above \'ncbi\' after make
	exit 1
fi

datafiles="humrep.fsa lineages.txt sequin.hlp asn2ff.prt bstdt.val \
featdef.val gc.val makerpt.prt objprt.prt pubkey.enc seqcode.val \
sgmlbb.ent taxlist.txt BLOSUM62 KSat.flt KSchoth.flt KSgc.flt \
KShopp.flt KSkyte.flt KSpur.flt KSpyr.flt \
BLOSUM45 BLOSUM80 PAM30 PAM70 KSpcc.mat"

configfiles="nlmstmanrc sequinrc ncbidtrc"

TOPDIR=`pwd`
configdir=$TOPDIR/ncbi/config/unix
datadir=$TOPDIR/ncbi/data
errmsgdir=$TOPDIR/ncbi/errmsg
sequindoc=$TOPDIR/ncbi/doc/sequin.htm
sequinimages=$TOPDIR/ncbi/doc/images/

#delete the old archive subdir
test -d archive && rm -rf archive
#make sure we have timestamp file
test -f ncbi/VERSION || date > ncbi/VERSION
for i in sequin entrez fa2htgs blast netblast asn2xml
do
	mkdir -p archive/$i/data
	for f in $datafiles
	do
		ln $datadir/$f archive/$i/data/
	done
	ln ncbi/VERSION archive/$i/VERSION
done

#
# FIXES 3/98

cat >archive/entrez/README.1st <<EOF
If you have not done so already, please refer to the
file at ftp://ftp.ncbi.nih.gov/entrez/README
EOF

cd ncbi/build

#entrez (now it is remote)
ln -f Nentrez entrez 2>/dev/null
f="entrez blastcl3 ../doc/firewall.txt"
ln $f ../../archive/entrez/ || exit 1
cat > ../../archive/entrez/Cn3D.ReadMe << EOF
Cn3D is now distributed separately from Network Entrez.
To download Cn3D please look at the Cn3D home page or ftp site:

http://www.ncbi.nlm.nih.gov/Structure/cn3d.html
ftp://ftp.ncbi.nih.gov/cn3d/
EOF

#sequin
ln -f Psequin sequin 2>/dev/null
f="sequin tbl2asn"
ln $f ../../archive/sequin/ || exit 1
cat > ../../archive/sequin/Cn3D.ReadMe << EOF
Cn3D is now distributed separately from Sequin.
To download Cn3D please look at the Cn3D home page or ftp site:

http://www.ncbi.nlm.nih.gov/Structure/cn3d.html
ftp://ftp.ncbi.nih.gov/cn3d/
EOF

#asn2xml
f="asn2xml ../doc/README.asn2xml ../doc/ncbixml.txt"
ln $f ../../archive/asn2xml/ || exit 1
#we don't need data dir in this archive
rm -rf ../../archive/asn2xml/data

#fa2htgs
f="fa2htgs"
ln $f ../../archive/fa2htgs/ || exit 1

#Cn3D
#disabled by Dima, 09/07/01
#f="Cn3D"
#ln $f ../../archive/cn3d

#blast
f="blastall blastpgp seedtop formatdb fastacmd copymat makemat \
impala bl2seq megablast blastclust rpsblast ../doc/README.imp \
../doc/README.bls ../doc/README.mbl ../doc/README.bcl ../doc/README.rps \
../doc/README.formatdb"
ln $f ../../archive/blast/ || exit 1

#netblast
f="blastcl3 ../doc/firewall.txt ../doc/README.nbl"
ln $f ../../archive/netblast/ || exit 1

#sequin data and images
cd ../../archive/sequin
mkdir config errmsg images
test -d $errmsgdir && ln $errmsgdir/* errmsg/
test -d $sequinimages && ln $sequinimages/* images/
test -r $sequindoc && ln $sequindoc .
for file in $configfiles
do
	test -r $configdir/$file && ln $configdir/$file config/
done

#cd back to archive
cd $TOPDIR/archive

case `uname -s` in
SunOS)
	case `uname -r` in
	4.1*)
		platform=sun
		;;
	*)
		if [ `uname -p` = i386 ] ; then
			platform=solarisintel
		else
			platform=solaris
		fi
		;;
	esac
	;;
IRIX*)
	case `uname -r` in
	4.*)
		platform=sgi4
		;;
	5.*)
		platform=sgi5
		;;
	6.5)
		platform=sgi-mips4
		;;
	6.[0-4])
		platform=sgi
		;;
	*)
		platform=sgi
		;;
	esac
	;;
Linux)
	if [ `uname -m` = ppc ] ; then
		platform=ppclinux
	else
		platform=linux
	fi
	;;
OSF1)
	platform=alphaOSF1
	;;
HP-UX)
	if [ `uname -m` = ia64 ] ; then
		platform=hpux_ia64
	else
		platform=hpux
	fi
	;;
FreeBSD)
	platform=freebsd
	;;
Darwin)
	platform=darwin
	;;
NetBSD)
	platform=netbsd
	;;
AIX)
	arch=`uname -M|sed 's/.*-//'`
	if [ $arch = 150 -o $arch = 170 -o $arch = 260 -o $arch = 270 ]
	then
		platform=ibm_pwr3
	else
		platform=ibm_auto
	fi
	;;
*)
	platform="`uname -s`.`uname -m`"
	platform=`echo $platform|tr '[A-Z]' '[a-z]'|tr ' ' '_'`
	;;
esac

echo PLATFORM is $platform
pwd

for A in sequin entrez fa2htgs
do
	cd $A
	#if [ $platform = "linux" ] ; then
	#	touch README.1st
	#fi

	if [ $platform = "solaris" ] ; then
		touch README.1st
		cat >>README.1st <<EOF
As of 5/29/1996, the Solaris executables distributed by NCBI no longer include
a statically-linked Motif library.  This is due to the manner in which
Sun distributes Motif libraries.  Users of Solaris version 2.4 and higher
will find the runtime shared Motif library on their system.  Users of Solaris
version 2.3 and earlier may need to either upgrade their systems or purchase
the Motif library separately.

It may be necessary to set your LD_LIBRARY_PATH environment variable to
point to the directory where this file, libXm.so.3 (the final digit may
vary), appears on your system.  E.g.
   setenv LD_LIBRARY_PATH /usr/dt/lib
EOF
	fi

	if [ $platform = "sun" ] ; then
		touch README.1st
		cat >>README.1st <<EOF
 ******************************************************************
 *          ! ! !   W A R N I N G   ! ! !                         *
 *                                                                *
 *  The NCBI Toolkit on                                           *
 *     Windows 16 bit                                             *
 *         and                                                    *
 *     SunOS 4.X platforms                                        *
 *                                                                *
 *     WILL NO LONGER BE SUPPORTED   after May 1, 1999            *
 *                                                                *
 ******************************************************************

EOF
	fi
	if [ $platform = "sgi5" ] ; then
		touch README.sgi5
		cat >>README.1st <<EOF
 *******************************************************************
 *          ! ! !   W A R N I N G   ! ! !                          *
 *                                                                 *
 *  The NCBI Toolkit binaries for IRIX5.X                          *
 *     WILL NO LONGER BE SUPPORTED AND BUILT after January 1, 2002 *
 *                                                                 *
 *******************************************************************

EOF
	fi
	#cd back to archive
	cd ..
done

#for A in sequin entrez fa2htgs cn3d blast netblast asn2xml
for A in sequin entrez fa2htgs blast netblast asn2xml
do
	cd $A
	tar cf ../$A.$platform.tar .
	rm -f ../$A.$platform.tar.Z
	compress < ../$A.$platform.tar > ../$A.$platform.tar.Z
	gzip < ../$A.$platform.tar > ../$A.$platform.tar.gz 2>/dev/null
	if [ $? != 0 ] ; then
		/usr/ncbi/bin/gzip < ../$A.$platform.tar > ../$A.$platform.tar.gz 2>/dev/null
	fi
	rm -f ../$A.$platform.tar
	# cd back to archive
	cd ..
	#and remove it
	rm -fr $A
done
exit 0

